server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pbt
    username: root
    password: tncksrhd12
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
  h2:
    console:
      enable: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        default_batch_fetch_size: 100
  logging:
    level:
        org.springframework.web: DEBUG
        org.hibernate.SQL: DEBUG  # Hibernate SQL 쿼리 로그 출력
        org.hibernate.type.descriptor.sql.BasicBinder: TRACE  # 쿼리 바인딩 값 출력
jwt:
 secret: my-secret-key

logging:
  level:
      org.springframework.web: DEBUG
      org.hibernate.SQL: DEBUG  # Hibernate SQL 쿼리 로그 출력
      org.hibernate.type.descriptor.sql.BasicBinder: TRACE  # 쿼리 바인딩 값 출력


thymeleaf:
  cache: false
  check-template-location: false
  enabled: true
  prefix: classpath:/static/templates
  suffix: .html
  view-names: /html/*